### ISSUE TITLE
Link to doc is 404 in README.md

### ISSUE THREAD

**Issue by xShirase** [riyadhalnur/npm-modules-sync#90]
Title self explanatory, the link goes to : https://github.com/riyadhalnur/npm-modules-sync/blob/master/docs/docs.md

**Comment by riyadhalnur** [comment]
Thanks for reporting. Will fix in next release

**Comment by sw-yx** [comment]
still 404ing here

**Comment by tonywoode** [comment]
its not just the link to the docs that's incorrect, the docs themselves seem to be missing: from the current branch, from all branches, from all previous commits and from the npm package where they are ignored

Could anyone tell me in the meantime how to use this? is it bascially, after installing on machines that you want to start syncing:
1) create new new github token and blank gist
2) run `npm-sync init -t 123e4567f89 -i 123456789`
3) run `npm-sync upload` on a machine that has global packages you want to sync
4) run `npm-sync download` on machines you want to sync up to the gist
5) after all machines are in sync, run `npm-sync upload` every time you add a global package on one of them, and `npm-sync download` on all other machines to get that package

**Comment by riyadhalnur** [comment]
I pushed a new release to remove the dead link. Added a `Getting Started` section in the README itself.

@tonywoode yes you have the basic gist of it down. Read more in the README to get you started if you're still stuck.

**Comment by tonywoode** [comment]
@riyadhalnur thanks very much, that's all that was needed, very impressive! I found one bug which I should open
I made a basic bash first-time installer (to sync TO a fresh machine, not to do the initial gist creation) in case it helps anyone: https://github.com/tonywoode/dotfiles/blob/master/sync-npm-modules
note in that I had a suggestion for the quickest way to pretty print the gist to see the entries, something most people would prob want to do before syncing (open browser console and `JSON.parse(document.getElementById('file-modules-json-LC1').textContent)`)
